### ISSUE TITLE
How to use ???

### ISSUE THREAD

**Issue by winbotscript** [gjbsaiia/easyJoinAPI#1]
Hello there,

Can u give me an example format foor use this API ???

**Comment by gjbsaiia** [comment]
Hey man, still working on it - give me a few days

**Comment by gjbsaiia** [comment]
Okay, I updated the build I'm using - still working out the kinks, but feel free to branch out and work on it. I included instructions in the main ReadMe. Hit me up if you have questions

**Comment by gjbsaiia** [comment]
Hey boss, this code all works now in my environment. You'll have to change some stuff to get it working in ur respective environment. But it's set up to run in a container. Depending on your security needs, you'll probably need to configure a [kerberos sidecar](https://blog.openshift.com/kerberos-sidecar-container/) for the api container
